name: crystalclear
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.0.3
  crypto: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  google_maps_flutter: ^2.5.3
  dropdown_button2: ^2.3.9
  permission_handler: ^11.3.1
  geolocator: ^11.0.0
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
  image_picker: ^0.8.4+3
  geocoding: ^3.0.0
  intl: ^0.17.0
  timeago: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/